version: "3"

services:
  calibration.api:
    image: calibrationapi
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: calibrationapi
    ports:
      - "8007:80"
    networks:
      - spectrum
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    restart: always

networks:
  spectrum:
    external: true
